<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>UE.PostOffice.Data</AssemblyName>
    <RootNamespace>UE.PostOffice.Data</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Linq.Queryable" Version="4.3.0" />
  </ItemGroup>

</Project>
