<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UE.PostOffice.Core\UE.PostOffice.Core.csproj" />
    <ProjectReference Include="..\UE.PostOffice.Data\UE.PostOffice.Data.csproj" />
  </ItemGroup>

</Project>
